### ISSUE TITLE
Player can see enemy team deatch chat

### ISSUE THREAD

**Issue by Nevvy** [SkyGuardian/Chat-Processor#23]
Game: CS:GO
SourceMod Version: 1.8.0.6020
Metamod:Source version 1.10.7-dev
[SM] Listing 2 plugins:
  01 "Chat-Processor" (2.0.9) by Keith Warren (Drixevel)
  02 "Token Auto Updater" (1.3.1) by ˙·٠●Феникс●٠·˙
Issue: 
sm_chatprocessor_deadchat doesnt work in CS:GO
But when i use sv_deadtalk 1 I see enemy team deatch chat

**Comment by T1MOXA** [comment]
The same problem

**Comment by mloveless1227** [comment]
Is this something that might get addressed? It seems to be a problem for many people.

**Comment by SSadistic** [comment]
Can confirm - enemy team chat is visible.

**Comment by Hexer10** [comment]
Merging https://github.com/SkyGuardian/Chat-Processor/pull/28 should be fixed.
